# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ingrese el nombre del producto', max_length=50)),
                ('provider', models.CharField(help_text='MichellStore', max_length=50)),
                ('typeproduct', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('A', 'Accesorios'), ('Z', 'Zapatos'), ('C', 'Cosmeticos')], help_text='Seleccione la Categoria del Producto', max_length=1)),
                ('color', models.CharField(choices=[('R', 'Rojo'), ('A', 'Azul'), ('M', 'Morado'), ('E', 'Esmeralda'), ('N', 'Negro')], help_text='Seleccione el Color del Producto', max_length=1)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
